/*
 * File: app/store/MimeTypeStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VMS.store.MimeTypeStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyStore',
            data: [
                {
                    extension: '.3dm',
                    type: 'x-world/x-3dmf'
                },
                {
                    extension: '.3dmf',
                    type: 'x-world/x-3dmf'
                },
                {
                    extension: '.a',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.aab',
                    type: 'application/x-authorware-bin'
                },
                {
                    extension: '.aam',
                    type: 'application/x-authorware-map'
                },
                {
                    extension: '.aas',
                    type: 'application/x-authorware-seg'
                },
                {
                    extension: '.abc',
                    type: 'text/vnd.abc'
                },
                {
                    extension: '.acgi',
                    type: 'text/html'
                },
                {
                    extension: '.afl',
                    type: 'video/animaflex'
                },
                {
                    extension: '.ai',
                    type: 'application/postscript'
                },
                {
                    extension: '.aif',
                    type: 'audio/aiff'
                },
                {
                    extension: '.aif',
                    type: 'audio/x-aiff'
                },
                {
                    extension: '.aifc',
                    type: 'audio/aiff'
                },
                {
                    extension: '.aifc',
                    type: 'audio/x-aiff'
                },
                {
                    extension: '.aiff',
                    type: 'audio/aiff'
                },
                {
                    extension: '.aiff',
                    type: 'audio/x-aiff'
                },
                {
                    extension: '.aim',
                    type: 'application/x-aim'
                },
                {
                    extension: '.aip',
                    type: 'text/x-audiosoft-intra'
                },
                {
                    extension: '.ani',
                    type: 'application/x-navi-animation'
                },
                {
                    extension: '.aos',
                    type: 'application/x-nokia-9000-communicator-add-on-software'
                },
                {
                    extension: '.aps',
                    type: 'application/mime'
                },
                {
                    extension: '.arc',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.arj',
                    type: 'application/arj'
                },
                {
                    extension: '.arj',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.art',
                    type: 'image/x-jg'
                },
                {
                    extension: '.asf',
                    type: 'video/x-ms-asf'
                },
                {
                    extension: '.asm',
                    type: 'text/x-asm'
                },
                {
                    extension: '.asp',
                    type: 'text/asp'
                },
                {
                    extension: '.asx',
                    type: 'application/x-mplayer2'
                },
                {
                    extension: '.asx',
                    type: 'video/x-ms-asf'
                },
                {
                    extension: '.asx',
                    type: 'video/x-ms-asf-plugin'
                },
                {
                    extension: '.au',
                    type: 'audio/basic'
                },
                {
                    extension: '.au',
                    type: 'audio/x-au'
                },
                {
                    extension: '.avi',
                    type: 'application/x-troff-msvideo'
                },
                {
                    extension: '.avi',
                    type: 'video/avi'
                },
                {
                    extension: '.avi',
                    type: 'video/msvideo'
                },
                {
                    extension: '.avi',
                    type: 'video/x-msvideo'
                },
                {
                    extension: '.avs',
                    type: 'video/avs-video'
                },
                {
                    extension: '.bcpio',
                    type: 'application/x-bcpio'
                },
                {
                    extension: '.bin',
                    type: 'application/mac-binary'
                },
                {
                    extension: '.bin',
                    type: 'application/macbinary'
                },
                {
                    extension: '.bin',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.bin',
                    type: 'application/x-binary'
                },
                {
                    extension: '.bin',
                    type: 'application/x-macbinary'
                },
                {
                    extension: '.bm',
                    type: 'image/bmp'
                },
                {
                    extension: '.bmp',
                    type: 'image/bmp'
                },
                {
                    extension: '.bmp',
                    type: 'image/x-windows-bmp'
                },
                {
                    extension: '.boo',
                    type: 'application/book'
                },
                {
                    extension: '.book',
                    type: 'application/book'
                },
                {
                    extension: '.boz',
                    type: 'application/x-bzip2'
                },
                {
                    extension: '.bsh',
                    type: 'application/x-bsh'
                },
                {
                    extension: '.bz',
                    type: 'application/x-bzip'
                },
                {
                    extension: '.bz2',
                    type: 'application/x-bzip2'
                },
                {
                    extension: '.c',
                    type: 'text/plain'
                },
                {
                    extension: '.c',
                    type: 'text/x-c'
                },
                {
                    extension: '.c++',
                    type: 'text/plain'
                },
                {
                    extension: '.cat',
                    type: 'application/vnd.ms-pki.seccat'
                },
                {
                    extension: '.cc',
                    type: 'text/plain'
                },
                {
                    extension: '.cc',
                    type: 'text/x-c'
                },
                {
                    extension: '.ccad',
                    type: 'application/clariscad'
                },
                {
                    extension: '.cco',
                    type: 'application/x-cocoa'
                },
                {
                    extension: '.cdf',
                    type: 'application/cdf'
                },
                {
                    extension: '.cdf',
                    type: 'application/x-cdf'
                },
                {
                    extension: '.cdf',
                    type: 'application/x-netcdf'
                },
                {
                    extension: '.cer',
                    type: 'application/pkix-cert'
                },
                {
                    extension: '.cer',
                    type: 'application/x-x509-ca-cert'
                },
                {
                    extension: '.cha',
                    type: 'application/x-chat'
                },
                {
                    extension: '.chat',
                    type: 'application/x-chat'
                },
                {
                    extension: '.class',
                    type: 'application/java'
                },
                {
                    extension: '.class',
                    type: 'application/java-byte-code'
                },
                {
                    extension: '.class',
                    type: 'application/x-java-class'
                },
                {
                    extension: '.com',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.com',
                    type: 'text/plain'
                },
                {
                    extension: '.conf',
                    type: 'text/plain'
                },
                {
                    extension: '.cpio',
                    type: 'application/x-cpio'
                },
                {
                    extension: '.cpp',
                    type: 'text/x-c'
                },
                {
                    extension: '.cpt',
                    type: 'application/mac-compactpro'
                },
                {
                    extension: '.cpt',
                    type: 'application/x-compactpro'
                },
                {
                    extension: '.cpt',
                    type: 'application/x-cpt'
                },
                {
                    extension: '.crl',
                    type: 'application/pkcs-crl'
                },
                {
                    extension: '.crl',
                    type: 'application/pkix-crl'
                },
                {
                    extension: '.crt',
                    type: 'application/pkix-cert'
                },
                {
                    extension: '.crt',
                    type: 'application/x-x509-ca-cert'
                },
                {
                    extension: '.crt',
                    type: 'application/x-x509-user-cert'
                },
                {
                    extension: '.csh',
                    type: 'application/x-csh'
                },
                {
                    extension: '.csh',
                    type: 'text/x-script.csh'
                },
                {
                    extension: '.css',
                    type: 'application/x-pointplus'
                },
                {
                    extension: '.css',
                    type: 'text/css'
                },
                {
                    extension: '.cxx',
                    type: 'text/plain'
                },
                {
                    extension: '.dcr',
                    type: 'application/x-director'
                },
                {
                    extension: '.deepv',
                    type: 'application/x-deepv'
                },
                {
                    extension: '.def',
                    type: 'text/plain'
                },
                {
                    extension: '.der',
                    type: 'application/x-x509-ca-cert'
                },
                {
                    extension: '.dif',
                    type: 'video/x-dv'
                },
                {
                    extension: '.dir',
                    type: 'application/x-director'
                },
                {
                    extension: '.dl',
                    type: 'video/dl'
                },
                {
                    extension: '.dl',
                    type: 'video/x-dl'
                },
                {
                    extension: '.doc',
                    type: 'application/msword'
                },
                {
                    extension: '.dot',
                    type: 'application/msword'
                },
                {
                    extension: '.dp',
                    type: 'application/commonground'
                },
                {
                    extension: '.drw',
                    type: 'application/drafting'
                },
                {
                    extension: '.dump',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.dv',
                    type: 'video/x-dv'
                },
                {
                    extension: '.dvi',
                    type: 'application/x-dvi'
                },
                {
                    extension: '.dwf',
                    type: 'drawing/x-dwf (old)'
                },
                {
                    extension: '.dwf',
                    type: 'model/vnd.dwf'
                },
                {
                    extension: '.dwg',
                    type: 'application/acad'
                },
                {
                    extension: '.dwg',
                    type: 'image/vnd.dwg'
                },
                {
                    extension: '.dwg',
                    type: 'image/x-dwg'
                },
                {
                    extension: '.dxf',
                    type: 'application/dxf'
                },
                {
                    extension: '.dxf',
                    type: 'image/vnd.dwg'
                },
                {
                    extension: '.dxf',
                    type: 'image/x-dwg'
                },
                {
                    extension: '.dxr',
                    type: 'application/x-director'
                },
                {
                    extension: '.el',
                    type: 'text/x-script.elisp'
                },
                {
                    extension: '.elc',
                    type: 'application/x-bytecode.elisp (compiled elisp)'
                },
                {
                    extension: '.elc',
                    type: 'application/x-elc'
                },
                {
                    extension: '.env',
                    type: 'application/x-envoy'
                },
                {
                    extension: '.eps',
                    type: 'application/postscript'
                },
                {
                    extension: '.es',
                    type: 'application/x-esrehber'
                },
                {
                    extension: '.etx',
                    type: 'text/x-setext'
                },
                {
                    extension: '.evy',
                    type: 'application/envoy'
                },
                {
                    extension: '.evy',
                    type: 'application/x-envoy'
                },
                {
                    extension: '.exe',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.f',
                    type: 'text/plain'
                },
                {
                    extension: '.f',
                    type: 'text/x-fortran'
                },
                {
                    extension: '.f77',
                    type: 'text/x-fortran'
                },
                {
                    extension: '.f90',
                    type: 'text/plain'
                },
                {
                    extension: '.f90',
                    type: 'text/x-fortran'
                },
                {
                    extension: '.fdf',
                    type: 'application/vnd.fdf'
                },
                {
                    extension: '.fif',
                    type: 'application/fractals'
                },
                {
                    extension: '.fif',
                    type: 'image/fif'
                },
                {
                    extension: '.fli',
                    type: 'video/fli'
                },
                {
                    extension: '.fli',
                    type: 'video/x-fli'
                },
                {
                    extension: '.flo',
                    type: 'image/florian'
                },
                {
                    extension: '.flx',
                    type: 'text/vnd.fmi.flexstor'
                },
                {
                    extension: '.fmf',
                    type: 'video/x-atomic3d-feature'
                },
                {
                    extension: '.for',
                    type: 'text/plain'
                },
                {
                    extension: '.for',
                    type: 'text/x-fortran'
                },
                {
                    extension: '.fpx',
                    type: 'image/vnd.fpx'
                },
                {
                    extension: '.fpx',
                    type: 'image/vnd.net-fpx'
                },
                {
                    extension: '.frl',
                    type: 'application/freeloader'
                },
                {
                    extension: '.funk',
                    type: 'audio/make'
                },
                {
                    extension: '.g',
                    type: 'text/plain'
                },
                {
                    extension: '.g3',
                    type: 'image/g3fax'
                },
                {
                    extension: '.gif',
                    type: 'image/gif'
                },
                {
                    extension: '.gl',
                    type: 'video/gl'
                },
                {
                    extension: '.gl',
                    type: 'video/x-gl'
                },
                {
                    extension: '.gsd',
                    type: 'audio/x-gsm'
                },
                {
                    extension: '.gsm',
                    type: 'audio/x-gsm'
                },
                {
                    extension: '.gsp',
                    type: 'application/x-gsp'
                },
                {
                    extension: '.gss',
                    type: 'application/x-gss'
                },
                {
                    extension: '.gtar',
                    type: 'application/x-gtar'
                },
                {
                    extension: '.gz',
                    type: 'application/x-compressed'
                },
                {
                    extension: '.gz',
                    type: 'application/x-gzip'
                },
                {
                    extension: '.gzip',
                    type: 'application/x-gzip'
                },
                {
                    extension: '.gzip',
                    type: 'multipart/x-gzip'
                },
                {
                    extension: '.h',
                    type: 'text/plain'
                },
                {
                    extension: '.h',
                    type: 'text/x-h'
                },
                {
                    extension: '.hdf',
                    type: 'application/x-hdf'
                },
                {
                    extension: '.help',
                    type: 'application/x-helpfile'
                },
                {
                    extension: '.hgl',
                    type: 'application/vnd.hp-hpgl'
                },
                {
                    extension: '.hh',
                    type: 'text/plain'
                },
                {
                    extension: '.hh',
                    type: 'text/x-h'
                },
                {
                    extension: '.hlb',
                    type: 'text/x-script'
                },
                {
                    extension: '.hlp',
                    type: 'application/hlp'
                },
                {
                    extension: '.hlp',
                    type: 'application/x-helpfile'
                },
                {
                    extension: '.hlp',
                    type: 'application/x-winhelp'
                },
                {
                    extension: '.hpg',
                    type: 'application/vnd.hp-hpgl'
                },
                {
                    extension: '.hpgl',
                    type: 'application/vnd.hp-hpgl'
                },
                {
                    extension: '.hqx',
                    type: 'application/binhex'
                },
                {
                    extension: '.hqx',
                    type: 'application/binhex4'
                },
                {
                    extension: '.hqx',
                    type: 'application/mac-binhex'
                },
                {
                    extension: '.hqx',
                    type: 'application/mac-binhex40'
                },
                {
                    extension: '.hqx',
                    type: 'application/x-binhex40'
                },
                {
                    extension: '.hqx',
                    type: 'application/x-mac-binhex40'
                },
                {
                    extension: '.hta',
                    type: 'application/hta'
                },
                {
                    extension: '.htc',
                    type: 'text/x-component'
                },
                {
                    extension: '.htm',
                    type: 'text/html'
                },
                {
                    extension: '.html',
                    type: 'text/html'
                },
                {
                    extension: '.htmls',
                    type: 'text/html'
                },
                {
                    extension: '.htt',
                    type: 'text/webviewhtml'
                },
                {
                    extension: '.htx',
                    type: 'text/html'
                },
                {
                    extension: '.ice',
                    type: 'x-conference/x-cooltalk'
                },
                {
                    extension: '.ico',
                    type: 'image/x-icon'
                },
                {
                    extension: '.idc',
                    type: 'text/plain'
                },
                {
                    extension: '.ief',
                    type: 'image/ief'
                },
                {
                    extension: '.iefs',
                    type: 'image/ief'
                },
                {
                    extension: '.iges',
                    type: 'application/iges'
                },
                {
                    extension: '.iges',
                    type: 'model/iges'
                },
                {
                    extension: '.igs',
                    type: 'application/iges'
                },
                {
                    extension: '.igs',
                    type: 'model/iges'
                },
                {
                    extension: '.ima',
                    type: 'application/x-ima'
                },
                {
                    extension: '.imap',
                    type: 'application/x-httpd-imap'
                },
                {
                    extension: '.inf',
                    type: 'application/inf'
                },
                {
                    extension: '.ins',
                    type: 'application/x-internett-signup'
                },
                {
                    extension: '.ip',
                    type: 'application/x-ip2'
                },
                {
                    extension: '.isu',
                    type: 'video/x-isvideo'
                },
                {
                    extension: '.it',
                    type: 'audio/it'
                },
                {
                    extension: '.iv',
                    type: 'application/x-inventor'
                },
                {
                    extension: '.ivr',
                    type: 'i-world/i-vrml'
                },
                {
                    extension: '.ivy',
                    type: 'application/x-livescreen'
                },
                {
                    extension: '.jam',
                    type: 'audio/x-jam'
                },
                {
                    extension: '.jav',
                    type: 'text/plain'
                },
                {
                    extension: '.jav',
                    type: 'text/x-java-source'
                },
                {
                    extension: '.java',
                    type: 'text/plain'
                },
                {
                    extension: '.java',
                    type: 'text/x-java-source'
                },
                {
                    extension: '.jcm',
                    type: 'application/x-java-commerce'
                },
                {
                    extension: '.jfif',
                    type: 'image/jpeg'
                },
                {
                    extension: '.jfif',
                    type: 'image/pjpeg'
                },
                {
                    extension: '.jfif-tbnl',
                    type: 'image/jpeg'
                },
                {
                    extension: '.jpe',
                    type: 'image/jpeg'
                },
                {
                    extension: '.jpe',
                    type: 'image/pjpeg'
                },
                {
                    extension: '.jpeg',
                    type: 'image/jpeg'
                },
                {
                    extension: '.jpeg',
                    type: 'image/pjpeg'
                },
                {
                    extension: '.jpg',
                    type: 'image/jpeg'
                },
                {
                    extension: '.jpg',
                    type: 'image/pjpeg'
                },
                {
                    extension: '.jps',
                    type: 'image/x-jps'
                },
                {
                    extension: '.js',
                    type: 'application/x-javascript'
                },
                {
                    extension: '.js',
                    type: 'application/javascript'
                },
                {
                    extension: '.js',
                    type: 'application/ecmascript'
                },
                {
                    extension: '.js',
                    type: 'text/javascript'
                },
                {
                    extension: '.js',
                    type: 'text/ecmascript'
                },
                {
                    extension: '.jut',
                    type: 'image/jutvision'
                },
                {
                    extension: '.kar',
                    type: 'audio/midi'
                },
                {
                    extension: '.kar',
                    type: 'music/x-karaoke'
                },
                {
                    extension: '.ksh',
                    type: 'application/x-ksh'
                },
                {
                    extension: '.ksh',
                    type: 'text/x-script.ksh'
                },
                {
                    extension: '.la',
                    type: 'audio/nspaudio'
                },
                {
                    extension: '.la',
                    type: 'audio/x-nspaudio'
                },
                {
                    extension: '.lam',
                    type: 'audio/x-liveaudio'
                },
                {
                    extension: '.latex',
                    type: 'application/x-latex'
                },
                {
                    extension: '.lha',
                    type: 'application/lha'
                },
                {
                    extension: '.lha',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.lha',
                    type: 'application/x-lha'
                },
                {
                    extension: '.lhx',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.list',
                    type: 'text/plain'
                },
                {
                    extension: '.lma',
                    type: 'audio/nspaudio'
                },
                {
                    extension: '.lma',
                    type: 'audio/x-nspaudio'
                },
                {
                    extension: '.log',
                    type: 'text/plain'
                },
                {
                    extension: '.lsp',
                    type: 'application/x-lisp'
                },
                {
                    extension: '.lsp',
                    type: 'text/x-script.lisp'
                },
                {
                    extension: '.lst',
                    type: 'text/plain'
                },
                {
                    extension: '.lsx',
                    type: 'text/x-la-asf'
                },
                {
                    extension: '.ltx',
                    type: 'application/x-latex'
                },
                {
                    extension: '.lzh',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.lzh',
                    type: 'application/x-lzh'
                },
                {
                    extension: '.lzx',
                    type: 'application/lzx'
                },
                {
                    extension: '.lzx',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.lzx',
                    type: 'application/x-lzx'
                },
                {
                    extension: '.m',
                    type: 'text/plain'
                },
                {
                    extension: '.m',
                    type: 'text/x-m'
                },
                {
                    extension: '.m1v',
                    type: 'video/mpeg'
                },
                {
                    extension: '.m2a',
                    type: 'audio/mpeg'
                },
                {
                    extension: '.m2v',
                    type: 'video/mpeg'
                },
                {
                    extension: '.m3u',
                    type: 'audio/x-mpequrl'
                },
                {
                    extension: '.man',
                    type: 'application/x-troff-man'
                },
                {
                    extension: '.map',
                    type: 'application/x-navimap'
                },
                {
                    extension: '.mar',
                    type: 'text/plain'
                },
                {
                    extension: '.mbd',
                    type: 'application/mbedlet'
                },
                {
                    extension: '.mc$',
                    type: 'application/x-magic-cap-package-1.0'
                },
                {
                    extension: '.mcd',
                    type: 'application/mcad'
                },
                {
                    extension: '.mcd',
                    type: 'application/x-mathcad'
                },
                {
                    extension: '.mcf',
                    type: 'image/vasa'
                },
                {
                    extension: '.mcf',
                    type: 'text/mcf'
                },
                {
                    extension: '.mcp',
                    type: 'application/netmc'
                },
                {
                    extension: '.me',
                    type: 'application/x-troff-me'
                },
                {
                    extension: '.mht',
                    type: 'message/rfc822'
                },
                {
                    extension: '.mhtml',
                    type: 'message/rfc822'
                },
                {
                    extension: '.mid',
                    type: 'application/x-midi'
                },
                {
                    extension: '.mid',
                    type: 'audio/midi'
                },
                {
                    extension: '.mid',
                    type: 'audio/x-mid'
                },
                {
                    extension: '.mid',
                    type: 'audio/x-midi'
                },
                {
                    extension: '.mid',
                    type: 'music/crescendo'
                },
                {
                    extension: '.mid',
                    type: 'x-music/x-midi'
                },
                {
                    extension: '.midi',
                    type: 'application/x-midi'
                },
                {
                    extension: '.midi',
                    type: 'audio/midi'
                },
                {
                    extension: '.midi',
                    type: 'audio/x-mid'
                },
                {
                    extension: '.midi',
                    type: 'audio/x-midi'
                },
                {
                    extension: '.midi',
                    type: 'music/crescendo'
                },
                {
                    extension: '.midi',
                    type: 'x-music/x-midi'
                },
                {
                    extension: '.mif',
                    type: 'application/x-frame'
                },
                {
                    extension: '.mif',
                    type: 'application/x-mif'
                },
                {
                    extension: '.mime',
                    type: 'message/rfc822'
                },
                {
                    extension: '.mime',
                    type: 'www/mime'
                },
                {
                    extension: '.mjf',
                    type: 'audio/x-vnd.audioexplosion.mjuicemediafile'
                },
                {
                    extension: '.mjpg',
                    type: 'video/x-motion-jpeg'
                },
                {
                    extension: '.mm',
                    type: 'application/base64'
                },
                {
                    extension: '.mm',
                    type: 'application/x-meme'
                },
                {
                    extension: '.mme',
                    type: 'application/base64'
                },
                {
                    extension: '.mod',
                    type: 'audio/mod'
                },
                {
                    extension: '.mod',
                    type: 'audio/x-mod'
                },
                {
                    extension: '.moov',
                    type: 'video/quicktime'
                },
                {
                    extension: '.mov',
                    type: 'video/quicktime'
                },
                {
                    extension: '.movie',
                    type: 'video/x-sgi-movie'
                },
                {
                    extension: '.mp2',
                    type: 'audio/mpeg'
                },
                {
                    extension: '.mp2',
                    type: 'audio/x-mpeg'
                },
                {
                    extension: '.mp2',
                    type: 'video/mpeg'
                },
                {
                    extension: '.mp2',
                    type: 'video/x-mpeg'
                },
                {
                    extension: '.mp2',
                    type: 'video/x-mpeq2a'
                },
                {
                    extension: '.mp3',
                    type: 'audio/mpeg3'
                },
                {
                    extension: '.mp3',
                    type: 'audio/x-mpeg-3'
                },
                {
                    extension: '.mp3',
                    type: 'video/mpeg'
                },
                {
                    extension: '.mp3',
                    type: 'video/x-mpeg'
                },
                {
                    extension: '.mpa',
                    type: 'audio/mpeg'
                },
                {
                    extension: '.mpa',
                    type: 'video/mpeg'
                },
                {
                    extension: '.mpc',
                    type: 'application/x-project'
                },
                {
                    extension: '.mpe',
                    type: 'video/mpeg'
                },
                {
                    extension: '.mpeg',
                    type: 'video/mpeg'
                },
                {
                    extension: '.mpg',
                    type: 'audio/mpeg'
                },
                {
                    extension: '.mpg',
                    type: 'video/mpeg'
                },
                {
                    extension: '.mpga',
                    type: 'audio/mpeg'
                },
                {
                    extension: '.mpp',
                    type: 'application/vnd.ms-project'
                },
                {
                    extension: '.mpt',
                    type: 'application/x-project'
                },
                {
                    extension: '.mpv',
                    type: 'application/x-project'
                },
                {
                    extension: '.mpx',
                    type: 'application/x-project'
                },
                {
                    extension: '.mrc',
                    type: 'application/marc'
                },
                {
                    extension: '.ms',
                    type: 'application/x-troff-ms'
                },
                {
                    extension: '.mv',
                    type: 'video/x-sgi-movie'
                },
                {
                    extension: '.my',
                    type: 'audio/make'
                },
                {
                    extension: '.mzz',
                    type: 'application/x-vnd.audioexplosion.mzz'
                },
                {
                    extension: '.nap',
                    type: 'image/naplps'
                },
                {
                    extension: '.naplps',
                    type: 'image/naplps'
                },
                {
                    extension: '.nc',
                    type: 'application/x-netcdf'
                },
                {
                    extension: '.ncm',
                    type: 'application/vnd.nokia.configuration-message'
                },
                {
                    extension: '.nif',
                    type: 'image/x-niff'
                },
                {
                    extension: '.niff',
                    type: 'image/x-niff'
                },
                {
                    extension: '.nix',
                    type: 'application/x-mix-transfer'
                },
                {
                    extension: '.nsc',
                    type: 'application/x-conference'
                },
                {
                    extension: '.nvd',
                    type: 'application/x-navidoc'
                },
                {
                    extension: '.o',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.oda',
                    type: 'application/oda'
                },
                {
                    extension: '.omc',
                    type: 'application/x-omc'
                },
                {
                    extension: '.omcd',
                    type: 'application/x-omcdatamaker'
                },
                {
                    extension: '.omcr',
                    type: 'application/x-omcregerator'
                },
                {
                    extension: '.p',
                    type: 'text/x-pascal'
                },
                {
                    extension: '.p10',
                    type: 'application/pkcs10'
                },
                {
                    extension: '.p10',
                    type: 'application/x-pkcs10'
                },
                {
                    extension: '.p12',
                    type: 'application/pkcs-12'
                },
                {
                    extension: '.p12',
                    type: 'application/x-pkcs12'
                },
                {
                    extension: '.p7a',
                    type: 'application/x-pkcs7-signature'
                },
                {
                    extension: '.p7c',
                    type: 'application/pkcs7-mime'
                },
                {
                    extension: '.p7c',
                    type: 'application/x-pkcs7-mime'
                },
                {
                    extension: '.p7m',
                    type: 'application/pkcs7-mime'
                },
                {
                    extension: '.p7m',
                    type: 'application/x-pkcs7-mime'
                },
                {
                    extension: '.p7r',
                    type: 'application/x-pkcs7-certreqresp'
                },
                {
                    extension: '.p7s',
                    type: 'application/pkcs7-signature'
                },
                {
                    extension: '.part',
                    type: 'application/pro_eng'
                },
                {
                    extension: '.pas',
                    type: 'text/pascal'
                },
                {
                    extension: '.pbm',
                    type: 'image/x-portable-bitmap'
                },
                {
                    extension: '.pcl',
                    type: 'application/vnd.hp-pcl'
                },
                {
                    extension: '.pcl',
                    type: 'application/x-pcl'
                },
                {
                    extension: '.pct',
                    type: 'image/x-pict'
                },
                {
                    extension: '.pcx',
                    type: 'image/x-pcx'
                },
                {
                    extension: '.pdb',
                    type: 'chemical/x-pdb'
                },
                {
                    extension: '.pdf',
                    type: 'application/pdf'
                },
                {
                    extension: '.pfunk',
                    type: 'audio/make'
                },
                {
                    extension: '.pfunk',
                    type: 'audio/make.my.funk'
                },
                {
                    extension: '.pgm',
                    type: 'image/x-portable-graymap'
                },
                {
                    extension: '.pgm',
                    type: 'image/x-portable-greymap'
                },
                {
                    extension: '.pic',
                    type: 'image/pict'
                },
                {
                    extension: '.pict',
                    type: 'image/pict'
                },
                {
                    extension: '.pkg',
                    type: 'application/x-newton-compatible-pkg'
                },
                {
                    extension: '.pko',
                    type: 'application/vnd.ms-pki.pko'
                },
                {
                    extension: '.pl',
                    type: 'text/plain'
                },
                {
                    extension: '.pl',
                    type: 'text/x-script.perl'
                },
                {
                    extension: '.plx',
                    type: 'application/x-pixclscript'
                },
                {
                    extension: '.pm',
                    type: 'image/x-xpixmap'
                },
                {
                    extension: '.pm',
                    type: 'text/x-script.perl-module'
                },
                {
                    extension: '.pm4',
                    type: 'application/x-pagemaker'
                },
                {
                    extension: '.pm5',
                    type: 'application/x-pagemaker'
                },
                {
                    extension: '.png',
                    type: 'image/png'
                },
                {
                    extension: '.pnm',
                    type: 'application/x-portable-anymap'
                },
                {
                    extension: '.pnm',
                    type: 'image/x-portable-anymap'
                },
                {
                    extension: '.pot',
                    type: 'application/mspowerpoint'
                },
                {
                    extension: '.pot',
                    type: 'application/vnd.ms-powerpoint'
                },
                {
                    extension: '.pov',
                    type: 'model/x-pov'
                },
                {
                    extension: '.ppa',
                    type: 'application/vnd.ms-powerpoint'
                },
                {
                    extension: '.ppm',
                    type: 'image/x-portable-pixmap'
                },
                {
                    extension: '.pps',
                    type: 'application/mspowerpoint'
                },
                {
                    extension: '.pps',
                    type: 'application/vnd.ms-powerpoint'
                },
                {
                    extension: '.ppt',
                    type: 'application/mspowerpoint'
                },
                {
                    extension: '.ppt',
                    type: 'application/powerpoint'
                },
                {
                    extension: '.ppt',
                    type: 'application/vnd.ms-powerpoint'
                },
                {
                    extension: '.ppt',
                    type: 'application/x-mspowerpoint'
                },
                {
                    extension: '.ppz',
                    type: 'application/mspowerpoint'
                },
                {
                    extension: '.pre',
                    type: 'application/x-freelance'
                },
                {
                    extension: '.prt',
                    type: 'application/pro_eng'
                },
                {
                    extension: '.ps',
                    type: 'application/postscript'
                },
                {
                    extension: '.psd',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.pvu',
                    type: 'paleovu/x-pv'
                },
                {
                    extension: '.pwz',
                    type: 'application/vnd.ms-powerpoint'
                },
                {
                    extension: '.py',
                    type: 'text/x-script.phyton'
                },
                {
                    extension: '.pyc',
                    type: 'applicaiton/x-bytecode.python'
                },
                {
                    extension: '.qcp',
                    type: 'audio/vnd.qcelp'
                },
                {
                    extension: '.qd3',
                    type: 'x-world/x-3dmf'
                },
                {
                    extension: '.qd3d',
                    type: 'x-world/x-3dmf'
                },
                {
                    extension: '.qif',
                    type: 'image/x-quicktime'
                },
                {
                    extension: '.qt',
                    type: 'video/quicktime'
                },
                {
                    extension: '.qtc',
                    type: 'video/x-qtc'
                },
                {
                    extension: '.qti',
                    type: 'image/x-quicktime'
                },
                {
                    extension: '.qtif',
                    type: 'image/x-quicktime'
                },
                {
                    extension: '.ra',
                    type: 'audio/x-pn-realaudio'
                },
                {
                    extension: '.ra',
                    type: 'audio/x-pn-realaudio-plugin'
                },
                {
                    extension: '.ra',
                    type: 'audio/x-realaudio'
                },
                {
                    extension: '.ram',
                    type: 'audio/x-pn-realaudio'
                },
                {
                    extension: '.ras',
                    type: 'application/x-cmu-raster'
                },
                {
                    extension: '.ras',
                    type: 'image/cmu-raster'
                },
                {
                    extension: '.ras',
                    type: 'image/x-cmu-raster'
                },
                {
                    extension: '.rast',
                    type: 'image/cmu-raster'
                },
                {
                    extension: '.rexx',
                    type: 'text/x-script.rexx'
                },
                {
                    extension: '.rf',
                    type: 'image/vnd.rn-realflash'
                },
                {
                    extension: '.rgb',
                    type: 'image/x-rgb'
                },
                {
                    extension: '.rm',
                    type: 'application/vnd.rn-realmedia'
                },
                {
                    extension: '.rm',
                    type: 'audio/x-pn-realaudio'
                },
                {
                    extension: '.rmi',
                    type: 'audio/mid'
                },
                {
                    extension: '.rmm',
                    type: 'audio/x-pn-realaudio'
                },
                {
                    extension: '.rmp',
                    type: 'audio/x-pn-realaudio'
                },
                {
                    extension: '.rmp',
                    type: 'audio/x-pn-realaudio-plugin'
                },
                {
                    extension: '.rng',
                    type: 'application/ringing-tones'
                },
                {
                    extension: '.rng',
                    type: 'application/vnd.nokia.ringing-tone'
                },
                {
                    extension: '.rnx',
                    type: 'application/vnd.rn-realplayer'
                },
                {
                    extension: '.roff',
                    type: 'application/x-troff'
                },
                {
                    extension: '.rp',
                    type: 'image/vnd.rn-realpix'
                },
                {
                    extension: '.rpm',
                    type: 'audio/x-pn-realaudio-plugin'
                },
                {
                    extension: '.rt',
                    type: 'text/richtext'
                },
                {
                    extension: '.rt',
                    type: 'text/vnd.rn-realtext'
                },
                {
                    extension: '.rtf',
                    type: 'application/rtf'
                },
                {
                    extension: '.rtf',
                    type: 'application/x-rtf'
                },
                {
                    extension: '.rtf',
                    type: 'text/richtext'
                },
                {
                    extension: '.rtx',
                    type: 'application/rtf'
                },
                {
                    extension: '.rtx',
                    type: 'text/richtext'
                },
                {
                    extension: '.rv',
                    type: 'video/vnd.rn-realvideo'
                },
                {
                    extension: '.s',
                    type: 'text/x-asm'
                },
                {
                    extension: '.s3m',
                    type: 'audio/s3m'
                },
                {
                    extension: '.saveme',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.sbk',
                    type: 'application/x-tbook'
                },
                {
                    extension: '.scm',
                    type: 'application/x-lotusscreencam'
                },
                {
                    extension: '.scm',
                    type: 'text/x-script.guile'
                },
                {
                    extension: '.scm',
                    type: 'text/x-script.scheme'
                },
                {
                    extension: '.scm',
                    type: 'video/x-scm'
                },
                {
                    extension: '.sdml',
                    type: 'text/plain'
                },
                {
                    extension: '.sdp',
                    type: 'application/sdp'
                },
                {
                    extension: '.sdp',
                    type: 'application/x-sdp'
                },
                {
                    extension: '.sdr',
                    type: 'application/sounder'
                },
                {
                    extension: '.sea',
                    type: 'application/sea'
                },
                {
                    extension: '.sea',
                    type: 'application/x-sea'
                },
                {
                    extension: '.set',
                    type: 'application/set'
                },
                {
                    extension: '.sgm',
                    type: 'text/sgml'
                },
                {
                    extension: '.sgm',
                    type: 'text/x-sgml'
                },
                {
                    extension: '.sgml',
                    type: 'text/sgml'
                },
                {
                    extension: '.sgml',
                    type: 'text/x-sgml'
                },
                {
                    extension: '.sh',
                    type: 'application/x-bsh'
                },
                {
                    extension: '.sh',
                    type: 'application/x-sh'
                },
                {
                    extension: '.sh',
                    type: 'application/x-shar'
                },
                {
                    extension: '.sh',
                    type: 'text/x-script.sh'
                },
                {
                    extension: '.shar',
                    type: 'application/x-bsh'
                },
                {
                    extension: '.shar',
                    type: 'application/x-shar'
                },
                {
                    extension: '.shtml',
                    type: 'text/html'
                },
                {
                    extension: '.shtml',
                    type: 'text/x-server-parsed-html'
                },
                {
                    extension: '.sid',
                    type: 'audio/x-psid'
                },
                {
                    extension: '.sit',
                    type: 'application/x-sit'
                },
                {
                    extension: '.sit',
                    type: 'application/x-stuffit'
                },
                {
                    extension: '.skd',
                    type: 'application/x-koan'
                },
                {
                    extension: '.skm',
                    type: 'application/x-koan'
                },
                {
                    extension: '.skp',
                    type: 'application/x-koan'
                },
                {
                    extension: '.skt',
                    type: 'application/x-koan'
                },
                {
                    extension: '.sl',
                    type: 'application/x-seelogo'
                },
                {
                    extension: '.smi',
                    type: 'application/smil'
                },
                {
                    extension: '.smil',
                    type: 'application/smil'
                },
                {
                    extension: '.snd',
                    type: 'audio/basic'
                },
                {
                    extension: '.snd',
                    type: 'audio/x-adpcm'
                },
                {
                    extension: '.sol',
                    type: 'application/solids'
                },
                {
                    extension: '.spc',
                    type: 'application/x-pkcs7-certificates'
                },
                {
                    extension: '.spc',
                    type: 'text/x-speech'
                },
                {
                    extension: '.spl',
                    type: 'application/futuresplash'
                },
                {
                    extension: '.spr',
                    type: 'application/x-sprite'
                },
                {
                    extension: '.sprite',
                    type: 'application/x-sprite'
                },
                {
                    extension: '.src',
                    type: 'application/x-wais-source'
                },
                {
                    extension: '.ssi',
                    type: 'text/x-server-parsed-html'
                },
                {
                    extension: '.ssm',
                    type: 'application/streamingmedia'
                },
                {
                    extension: '.sst',
                    type: 'application/vnd.ms-pki.certstore'
                },
                {
                    extension: '.step',
                    type: 'application/step'
                },
                {
                    extension: '.stl',
                    type: 'application/sla'
                },
                {
                    extension: '.stl',
                    type: 'application/vnd.ms-pki.stl'
                },
                {
                    extension: '.stl',
                    type: 'application/x-navistyle'
                },
                {
                    extension: '.stp',
                    type: 'application/step'
                },
                {
                    extension: '.sv4cpio',
                    type: 'application/x-sv4cpio'
                },
                {
                    extension: '.sv4crc',
                    type: 'application/x-sv4crc'
                },
                {
                    extension: '.svf',
                    type: 'image/vnd.dwg'
                },
                {
                    extension: '.svf',
                    type: 'image/x-dwg'
                },
                {
                    extension: '.svr',
                    type: 'application/x-world'
                },
                {
                    extension: '.svr',
                    type: 'x-world/x-svr'
                },
                {
                    extension: '.swf',
                    type: 'application/x-shockwave-flash'
                },
                {
                    extension: '.t',
                    type: 'application/x-troff'
                },
                {
                    extension: '.talk',
                    type: 'text/x-speech'
                },
                {
                    extension: '.tar',
                    type: 'application/x-tar'
                },
                {
                    extension: '.tbk',
                    type: 'application/toolbook'
                },
                {
                    extension: '.tbk',
                    type: 'application/x-tbook'
                },
                {
                    extension: '.tcl',
                    type: 'application/x-tcl'
                },
                {
                    extension: '.tcl',
                    type: 'text/x-script.tcl'
                },
                {
                    extension: '.tcsh',
                    type: 'text/x-script.tcsh'
                },
                {
                    extension: '.tex',
                    type: 'application/x-tex'
                },
                {
                    extension: '.texi',
                    type: 'application/x-texinfo'
                },
                {
                    extension: '.texinfo',
                    type: 'application/x-texinfo'
                },
                {
                    extension: '.text',
                    type: 'application/plain'
                },
                {
                    extension: '.text',
                    type: 'text/plain'
                },
                {
                    extension: '.tgz',
                    type: 'application/gnutar'
                },
                {
                    extension: '.tgz',
                    type: 'application/x-compressed'
                },
                {
                    extension: '.tif',
                    type: 'image/tiff'
                },
                {
                    extension: '.tif',
                    type: 'image/x-tiff'
                },
                {
                    extension: '.tiff',
                    type: 'image/tiff'
                },
                {
                    extension: '.tiff',
                    type: 'image/x-tiff'
                },
                {
                    extension: '.tr',
                    type: 'application/x-troff'
                },
                {
                    extension: '.tsi',
                    type: 'audio/tsp-audio'
                },
                {
                    extension: '.tsp',
                    type: 'application/dsptype'
                },
                {
                    extension: '.tsp',
                    type: 'audio/tsplayer'
                },
                {
                    extension: '.tsv',
                    type: 'text/tab-separated-values'
                },
                {
                    extension: '.turbot',
                    type: 'image/florian'
                },
                {
                    extension: '.txt',
                    type: 'text/plain'
                },
                {
                    extension: '.uil',
                    type: 'text/x-uil'
                },
                {
                    extension: '.uni',
                    type: 'text/uri-list'
                },
                {
                    extension: '.unis',
                    type: 'text/uri-list'
                },
                {
                    extension: '.unv',
                    type: 'application/i-deas'
                },
                {
                    extension: '.uri',
                    type: 'text/uri-list'
                },
                {
                    extension: '.uris',
                    type: 'text/uri-list'
                },
                {
                    extension: '.ustar',
                    type: 'application/x-ustar'
                },
                {
                    extension: '.ustar',
                    type: 'multipart/x-ustar'
                },
                {
                    extension: '.uu',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.uu',
                    type: 'text/x-uuencode'
                },
                {
                    extension: '.uue',
                    type: 'text/x-uuencode'
                },
                {
                    extension: '.vcd',
                    type: 'application/x-cdlink'
                },
                {
                    extension: '.vcs',
                    type: 'text/x-vcalendar'
                },
                {
                    extension: '.vda',
                    type: 'application/vda'
                },
                {
                    extension: '.vdo',
                    type: 'video/vdo'
                },
                {
                    extension: '.vew',
                    type: 'application/groupwise'
                },
                {
                    extension: '.viv',
                    type: 'video/vivo'
                },
                {
                    extension: '.viv',
                    type: 'video/vnd.vivo'
                },
                {
                    extension: '.vivo',
                    type: 'video/vivo'
                },
                {
                    extension: '.vivo',
                    type: 'video/vnd.vivo'
                },
                {
                    extension: '.vmd',
                    type: 'application/vocaltec-media-desc'
                },
                {
                    extension: '.vmf',
                    type: 'application/vocaltec-media-file'
                },
                {
                    extension: '.voc',
                    type: 'audio/voc'
                },
                {
                    extension: '.voc',
                    type: 'audio/x-voc'
                },
                {
                    extension: '.vos',
                    type: 'video/vosaic'
                },
                {
                    extension: '.vox',
                    type: 'audio/voxware'
                },
                {
                    extension: '.vqe',
                    type: 'audio/x-twinvq-plugin'
                },
                {
                    extension: '.vqf',
                    type: 'audio/x-twinvq'
                },
                {
                    extension: '.vql',
                    type: 'audio/x-twinvq-plugin'
                },
                {
                    extension: '.vrml',
                    type: 'application/x-vrml'
                },
                {
                    extension: '.vrml',
                    type: 'model/vrml'
                },
                {
                    extension: '.vrml',
                    type: 'x-world/x-vrml'
                },
                {
                    extension: '.vrt',
                    type: 'x-world/x-vrt'
                },
                {
                    extension: '.vsd',
                    type: 'application/x-visio'
                },
                {
                    extension: '.vst',
                    type: 'application/x-visio'
                },
                {
                    extension: '.vsw',
                    type: 'application/x-visio'
                },
                {
                    extension: '.w60',
                    type: 'application/wordperfect6.0'
                },
                {
                    extension: '.w61',
                    type: 'application/wordperfect6.1'
                },
                {
                    extension: '.w6w',
                    type: 'application/msword'
                },
                {
                    extension: '.wav',
                    type: 'audio/wav'
                },
                {
                    extension: '.wav',
                    type: 'audio/x-wav'
                },
                {
                    extension: '.wb1',
                    type: 'application/x-qpro'
                },
                {
                    extension: '.wbmp',
                    type: 'image/vnd.wap.wbmp'
                },
                {
                    extension: '.web',
                    type: 'application/vnd.xara'
                },
                {
                    extension: '.wiz',
                    type: 'application/msword'
                },
                {
                    extension: '.wk1',
                    type: 'application/x-123'
                },
                {
                    extension: '.wmf',
                    type: 'windows/metafile'
                },
                {
                    extension: '.wml',
                    type: 'text/vnd.wap.wml'
                },
                {
                    extension: '.wmlc',
                    type: 'application/vnd.wap.wmlc'
                },
                {
                    extension: '.wmls',
                    type: 'text/vnd.wap.wmlscript'
                },
                {
                    extension: '.wmlsc',
                    type: 'application/vnd.wap.wmlscriptc'
                },
                {
                    extension: '.word',
                    type: 'application/msword'
                },
                {
                    extension: '.wp',
                    type: 'application/wordperfect'
                },
                {
                    extension: '.wp5',
                    type: 'application/wordperfect'
                },
                {
                    extension: '.wp5',
                    type: 'application/wordperfect6.0'
                },
                {
                    extension: '.wp6',
                    type: 'application/wordperfect'
                },
                {
                    extension: '.wpd',
                    type: 'application/wordperfect'
                },
                {
                    extension: '.wpd',
                    type: 'application/x-wpwin'
                },
                {
                    extension: '.wq1',
                    type: 'application/x-lotus'
                },
                {
                    extension: '.wri',
                    type: 'application/mswrite'
                },
                {
                    extension: '.wri',
                    type: 'application/x-wri'
                },
                {
                    extension: '.wrl',
                    type: 'application/x-world'
                },
                {
                    extension: '.wrl',
                    type: 'model/vrml'
                },
                {
                    extension: '.wrl',
                    type: 'x-world/x-vrml'
                },
                {
                    extension: '.wrz',
                    type: 'model/vrml'
                },
                {
                    extension: '.wrz',
                    type: 'x-world/x-vrml'
                },
                {
                    extension: '.wsc',
                    type: 'text/scriplet'
                },
                {
                    extension: '.wsrc',
                    type: 'application/x-wais-source'
                },
                {
                    extension: '.wtk',
                    type: 'application/x-wintalk'
                },
                {
                    extension: '.xbm',
                    type: 'image/x-xbitmap'
                },
                {
                    extension: '.xbm',
                    type: 'image/x-xbm'
                },
                {
                    extension: '.xbm',
                    type: 'image/xbm'
                },
                {
                    extension: '.xdr',
                    type: 'video/x-amt-demorun'
                },
                {
                    extension: '.xgz',
                    type: 'xgl/drawing'
                },
                {
                    extension: '.xif',
                    type: 'image/vnd.xiff'
                },
                {
                    extension: '.xl',
                    type: 'application/excel'
                },
                {
                    extension: '.xla',
                    type: 'application/excel'
                },
                {
                    extension: '.xla',
                    type: 'application/x-excel'
                },
                {
                    extension: '.xla',
                    type: 'application/x-msexcel'
                },
                {
                    extension: '.xlb',
                    type: 'application/excel'
                },
                {
                    extension: '.xlb',
                    type: 'application/vnd.ms-excel'
                },
                {
                    extension: '.xlb',
                    type: 'application/x-excel'
                },
                {
                    extension: '.xlc',
                    type: 'application/excel'
                },
                {
                    extension: '.xlc',
                    type: 'application/vnd.ms-excel'
                },
                {
                    extension: '.xlc',
                    type: 'application/x-excel'
                },
                {
                    extension: '.xld',
                    type: 'application/excel'
                },
                {
                    extension: '.xld',
                    type: 'application/x-excel'
                },
                {
                    extension: '.xlk',
                    type: 'application/excel'
                },
                {
                    extension: '.xlk',
                    type: 'application/x-excel'
                },
                {
                    extension: '.xll',
                    type: 'application/excel'
                },
                {
                    extension: '.xll',
                    type: 'application/vnd.ms-excel'
                },
                {
                    extension: '.xll',
                    type: 'application/x-excel'
                },
                {
                    extension: '.xlm',
                    type: 'application/excel'
                },
                {
                    extension: '.xlm',
                    type: 'application/vnd.ms-excel'
                },
                {
                    extension: '.xlm',
                    type: 'application/x-excel'
                },
                {
                    extension: '.xls',
                    type: 'application/excel'
                },
                {
                    extension: '.xls',
                    type: 'application/vnd.ms-excel'
                },
                {
                    extension: '.xls',
                    type: 'application/x-excel'
                },
                {
                    extension: '.xls',
                    type: 'application/x-msexcel'
                },
                {
                    extension: '.xlt',
                    type: 'application/excel'
                },
                {
                    extension: '.xlt',
                    type: 'application/x-excel'
                },
                {
                    extension: '.xlv',
                    type: 'application/excel'
                },
                {
                    extension: '.xlv',
                    type: 'application/x-excel'
                },
                {
                    extension: '.xlw',
                    type: 'application/excel'
                },
                {
                    extension: '.xlw',
                    type: 'application/vnd.ms-excel'
                },
                {
                    extension: '.xlw',
                    type: 'application/x-excel'
                },
                {
                    extension: '.xlw',
                    type: 'application/x-msexcel'
                },
                {
                    extension: '.xm',
                    type: 'audio/xm'
                },
                {
                    extension: '.xml',
                    type: 'application/xml'
                },
                {
                    extension: '.xml',
                    type: 'text/xml'
                },
                {
                    extension: '.xmz',
                    type: 'xgl/movie'
                },
                {
                    extension: '.xpix',
                    type: 'application/x-vnd.ls-xpix'
                },
                {
                    extension: '.xpm',
                    type: 'image/x-xpixmap'
                },
                {
                    extension: '.xpm',
                    type: 'image/xpm'
                },
                {
                    extension: '.x-png',
                    type: 'image/png'
                },
                {
                    extension: '.xsr',
                    type: 'video/x-amt-showrun'
                },
                {
                    extension: '.xwd',
                    type: 'image/x-xwd'
                },
                {
                    extension: '.xwd',
                    type: 'image/x-xwindowdump'
                },
                {
                    extension: '.xyz',
                    type: 'chemical/x-pdb'
                },
                {
                    extension: '.z',
                    type: 'application/x-compress'
                },
                {
                    extension: '.z',
                    type: 'application/x-compressed'
                },
                {
                    extension: '.zip',
                    type: 'application/x-compressed'
                },
                {
                    extension: '.zip',
                    type: 'application/x-zip-compressed'
                },
                {
                    extension: '.zip',
                    type: 'application/zip'
                },
                {
                    extension: '.zip',
                    type: 'multipart/x-zip'
                },
                {
                    extension: '.zoo',
                    type: 'application/octet-stream'
                },
                {
                    extension: '.zsh',
                    type: 'text/x-script.zsh'
                }
            ],
            fields: [
                {
                    name: 'extension',
                    type: 'string'
                },
                {
                    name: 'type',
                    type: 'string'
                }
            ]
        }, cfg)]);
    }
});