/*
 * File: app/controller/WorkplaceSectionController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VMS.controller.WorkplaceSectionController', {
    extend: 'Ext.app.Controller',

    stores: [
        'MultipartUploadStore',
        'S3ResourceStore'
    ],
    views: [
        'WorkplaceSection',
        'PartUploadPanel',
        'UploadPanel'
    ],

    refs: [
        {
            ref: 'mainBody',
            selector: '#mainBody'
        }
    ],

    onClickOnSection: function(button, e, eOpts) {
        if (button.getItemId() === "inProgressBtn") {	
            this.getMainBody().removeAll();
            this.getMainBody().add(this.getView('PartUploadPanel').create());
        }
    },

    onMenuitemClick: function(item, e, eOpts) {
        if (item.getItemId() === "uploadMineMenuItem" || item.getItemId() === "uploadEveryoneMenuItem") {
            this.getMainBody().removeAll();
            this.getMainBody().add(this.getView('UploadPanel').create());
        }
    },

    onComponentUploadFinish: function(eventOptions) {
        this.getStore('S3ResourceStore').reload();
    },

    init: function(application) {
        this.control({
            "#workplaceSection #uploadSection button": {
                click: this.onClickOnSection
            },
            "menuitem": {
                click: this.onMenuitemClick
            },
            "#uploadSection s3upload": {
                uploadFinish: this.onComponentUploadFinish
            }
        });
    }

});
