tpg_s3upload:
    resource:   @TpgS3UploadBundle/Resources/config/routing.yml
    prefix:     /api
    type:       rest

tpg_resource:
    resource:   @TpgResourceBundle/Resources/config/routing.yml
    prefix:     /api
    type:       rest