/*
 * File: app/model/MultipartUpload.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VMS.model.MultipartUpload', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'upload_id',
            type: 'string'
        },
        {
            name: 'completed_part',
            type: 'auto'
        },
        {
            name: 'created_at',
            type: 'date'
        },
        {
            name: 'updated_at',
            type: 'date'
        },
        {
            name: 'key',
            type: 'string'
        },
        {
            name: 'bucket',
            type: 'string'
        },
        {
            name: 'size_per_part',
            type: 'int'
        },
        {
            name: 'size',
            type: 'int'
        },
        {
            name: 'status',
            type: 'int'
        },
        {
            name: 'mime_type',
            type: 'string'
        },
        {
            name: 'number_of_part',
            type: 'int'
        },
        {
            defaultValue: false,
            name: 'uploading',
            type: 'boolean'
        }
    ]
});