/*
 * File: app/model/S3Resources.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VMS.model.S3Resources', {
    extend: 'Ext.data.Model',

    uses: [
        'VMS.model.Tag'
    ],

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'bucket',
            type: 'string'
        },
        {
            name: 'key',
            type: 'string'
        },
        {
            name: 'created_at',
            type: 'date'
        },
        {
            name: 'updated_at',
            type: 'date'
        },
        {
            name: 'mime_type',
            type: 'string'
        },
        {
            name: 'type',
            type: 'string'
        },
        {
            name: 'tag_id',
            type: 'int'
        }
    ],

    belongsTo: {
        associationKey: 'tag_id',
        model: 'VMS.model.Tag',
        foreignKey: 'tag_id',
        getterName: 'getTag',
        setterName: 'setTag'
    },

    proxy: {
        type: 'rest',
        url: '/api/s3/resources',
        format: 'json',
        reader: {
            type: 'json'
        }
    }
});