/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VMS.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'VMS.view.WorkplaceSection'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    floatable: false,
                    region: 'center',
                    split: false,
                    splitterResize: false,
                    itemId: 'mainBody',
                    style: {
                        'background-image': 'url(\'/images/seamless-abstract-squares-1042.png\')',
                        'background-repeat': 'repeat'
                    },
                    layout: {
                        type: 'fit'
                    }
                },
                {
                    xtype: 'workplace_section',
                    itemId: 'workplaceSection',
                    title: 'Workplace Section',
                    floatable: false,
                    region: 'west',
                    split: true,
                    splitterResize: false
                }
            ]
        });

        me.callParent(arguments);
    }

});