/*
 * File: app/view/TagTree.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VMS.view.TagTree', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.TagTree',

    requires: [
        'VMS.view.override.TagTree'
    ],

    frameHeader: false,
    header: false,
    manageHeight: false,
    title: 'My Tree Panel',
    titleCollapse: false,
    hideHeaders: true,
    scroll: true,
    store: 'TagStore',
    displayField: 'name',
    rootVisible: false,
    useArrows: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {
                rootVisible: false
            },
            selModel: Ext.create('Ext.selection.RowModel', {
                mode: 'MULTI'
            }),
            columns: [
                {
                    xtype: 'treecolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return value + " (" + record.get('count') + ")";
                    },
                    dataIndex: 'name',
                    text: 'Name',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    }

});