/*
 * File: app/view/UploadPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VMS.view.UploadPanel', {
    extend: 'Ext.panel.Panel',

    itemId: 'uploadPanel',
    layout: {
        align: 'stretch',
        padding: 10,
        type: 'vbox'
    },
    closable: true,
    title: 'Uploads',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldcontainer',
                    width: 400,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'Search'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            margins: '0 0 0 10'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 2,
                    itemId: 'uploadGrid',
                    header: false,
                    title: 'My Grid Panel',
                    store: 'S3ResourceStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'key',
                            text: 'Resource',
                            flex: 2
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'created_at',
                            text: 'Created On',
                            flex: 1,
                            format: 'd-m-Y H:i:s'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'mime_type',
                            emptyCellText: 'Unknown',
                            menuText: '',
                            text: 'Mime Type'
                        }
                    ],
                    viewConfig: {
                        plugins: [
                            Ext.create('Ext.grid.plugin.DragDrop', {

                            })
                        ]
                    },
                    selModel: Ext.create('Ext.selection.RowModel', {
                        mode: 'MULTI'
                    })
                }
            ],
            tools: [
                {
                    xtype: 'tool',
                    itemId: 'refresh',
                    tooltip: 'Refresh Grid',
                    type: 'refresh'
                }
            ]
        });

        me.callParent(arguments);
    }

});