/*
 * File: app/view/WorkplaceSection.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VMS.view.WorkplaceSection', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.workplace_section',

    requires: [
        'VMS.view.S3Upload',
        'VMS.view.TagTree'
    ],

    itemId: 'workplaceSection',
    width: 300,
    layout: {
        titleCollapse: false,
        hideCollapseTool: true,
        animate: true,
        sequence: false,
        multi: true,
        type: 'accordion'
    },
    collapsed: false,
    collapsible: true,
    header: false,
    title: 'Workplace',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    border: 1,
                    itemId: 'uploadSection',
                    defaults: {
                        padding: 10,
                        margin: 5
                    },
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyBorder: false,
                    bodyPadding: '',
                    collapsible: true,
                    frameHeader: false,
                    title: 'Uploads',
                    items: [
                        {
                            xtype: 'menu',
                            flex: 1,
                            floating: false,
                            width: 120,
                            items: [
                                {
                                    xtype: 's3upload',
                                    progressBar: true
                                },
                                {
                                    xtype: 'menuitem',
                                    cls: 'menu-item-32',
                                    itemId: 'inProgress',
                                    icon: '/images/works-in-progress-icon.png',
                                    iconCls: 'icon_32',
                                    text: 'In Progress'
                                },
                                {
                                    xtype: 'menuitem',
                                    cls: 'menu-item-32',
                                    itemId: 'myComplete',
                                    icon: '/images/my-folder.png',
                                    text: 'My Completed'
                                },
                                {
                                    xtype: 'menuitem',
                                    cls: 'menu-item-32',
                                    itemId: 'othersComplete',
                                    icon: '/images/other-folder.png',
                                    text: 'Others Completed'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'resourceSection',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    collapsible: true,
                    title: 'Resources',
                    items: [
                        {
                            xtype: 'textfield',
                            itemId: 'newTag',
                            padding: 5,
                            hideLabel: true,
                            enableKeyEvents: true
                        },
                        {
                            xtype: 'TagTree',
                            flex: 1
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});